#!/usr/bin/env bash
# OPTIONAL alternative router from the video (llama-swap). The default stack
# uses the built-in llama-server router from 02_start_engine.sh; run this
# instead when you want the video's fallback router. It downloads a pinned
# release binary into the project-local stack directory on first run.
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=_common.sh
source "$SCRIPT_DIR/_common.sh"
require_engine
require_command curl
require_command jq
require_command tar
require_command sha256sum
curl_auth_args

MODEL_LOAD_TIMEOUT="${MODEL_LOAD_TIMEOUT:-900}"
tarball="llama-swap_${LLAMA_SWAP_VERSION}_linux_amd64.tar.gz"
download_url="https://github.com/mostlygeek/llama-swap/releases/download/v${LLAMA_SWAP_VERSION}/${tarball}"
llama_swap_bin="$LLAMA_SWAP_DIR/llama-swap"
config_file="$LLAMA_SWAP_DIR/config.yaml"

mkdir -p "$LLAMA_SWAP_DIR"

if [[ ! -x "$llama_swap_bin" ]]; then
  printf 'Downloading pinned llama-swap v%s...\n' "$LLAMA_SWAP_VERSION"
  curl --fail --location --max-time 300 -o "$LLAMA_SWAP_DIR/$tarball" "$download_url"
  actual_sha256="$(sha256sum "$LLAMA_SWAP_DIR/$tarball" | cut -d ' ' -f 1)"
  if [[ "$actual_sha256" != "$LLAMA_SWAP_SHA256" ]]; then
    printf 'SHA-256 mismatch for %s\nexpected: %s\nactual:   %s\n' \
      "$tarball" "$LLAMA_SWAP_SHA256" "$actual_sha256" >&2
    exit 1
  fi
  tar -xzf "$LLAMA_SWAP_DIR/$tarball" -C "$LLAMA_SWAP_DIR"
  require_file "$llama_swap_bin"
fi
"$llama_swap_bin" --version || \
  printf 'WARN: llama-swap --version unsupported; continuing (checksum already verified).\n' >&2

# Generate the llama-swap config; the upstream command reuses the exact
# project-01 binary and the same placement arguments as the router preset.
mapfile -t model_args < <(engine_model_args)
{
  printf '# Generated by 03_llama_swap_alt.sh; edit config.env instead.\n'
  printf 'models:\n'
  printf '  %s:\n' "$MODEL_ALIAS"
  printf '    cmd: >\n'
  printf '      %s --port ${PORT} --host 127.0.0.1\n' "$LLAMA_SERVER"
  printf '      --model %s\n' "$MODEL_PATH"
  printf '      --alias %s\n' "$MODEL_ALIAS"
  printf '      %s\n' "${model_args[*]}"
} >"$config_file"
printf 'Wrote llama-swap config: %s\n' "$config_file"

if [[ -f "$LLAMA_SWAP_PID_FILE" ]] && kill -0 "$(cat "$LLAMA_SWAP_PID_FILE")" 2>/dev/null; then
  printf 'llama-swap already running (PID %s). Run scripts/09_stop_stack.sh first to restart it.\n' \
    "$(cat "$LLAMA_SWAP_PID_FILE")"
  exit 0
fi
rm -f "$LLAMA_SWAP_PID_FILE"

require_port_free "$LLAMA_SWAP_PORT"

run_id="llama_swap_$(timestamp)"
log_file="$RESULTS_DIR/${run_id}.log"

swap_pid=""
cleanup_on_error() {
  if [[ -n "$swap_pid" ]]; then
    kill "$swap_pid" 2>/dev/null || true
    wait "$swap_pid" 2>/dev/null || true
    rm -f "$LLAMA_SWAP_PID_FILE"
    printf 'llama-swap start failed and was rolled back; inspect %s\n' "$log_file" >&2
  fi
}
trap cleanup_on_error ERR

log_command "$log_file" "$llama_swap_bin" --config "$config_file" --listen "127.0.0.1:$LLAMA_SWAP_PORT"
nohup "$llama_swap_bin" --config "$config_file" --listen "127.0.0.1:$LLAMA_SWAP_PORT" \
  >>"$log_file" 2>&1 &
swap_pid=$!
printf '%s\n' "$swap_pid" >"$LLAMA_SWAP_PID_FILE"

swap_base_url="http://127.0.0.1:$LLAMA_SWAP_PORT"
if ! wait_http "$swap_base_url/health" 60; then
  printf 'llama-swap did not start; inspect %s\n' "$log_file" >&2
  exit 1
fi

printf 'Sending routed chat request (first call spawns the upstream and loads about 21 GB)...\n'
response_file="$RESULTS_DIR/${run_id}_smoke.json"
http_code="$(curl --silent --max-time "$MODEL_LOAD_TIMEOUT" \
  -H 'Content-Type: application/json' \
  -o "$response_file" -w '%{http_code}' \
  -d "$(jq -nc --arg model "$MODEL_ALIAS" --arg prompt "$SMOKE_PROMPT" \
    '{model:$model,messages:[{role:"user",content:$prompt}],max_tokens:'"$SMOKE_MAX_TOKENS"',temperature:0,seed:42}')" \
  "$swap_base_url/v1/chat/completions")"

if [[ "$http_code" != "200" ]]; then
  printf 'llama-swap chat completion returned HTTP %s; inspect %s and %s\n' \
    "$http_code" "$response_file" "$log_file" >&2
  exit 1
fi

printf 'Smoke response: %s\n' "$(jq -r '.choices[0].message.content' "$response_file")"
trap - ERR

printf '\nllama-swap is up: %s (model "%s", log %s)\n' "$swap_base_url" "$MODEL_ALIAS" "$log_file"
printf 'Point stack tools at this base URL instead of %s to use the alternative router.\n' "$ENGINE_BASE_URL"
printf 'PID %s recorded in %s. Stop with scripts/09_stop_stack.sh.\n' "$swap_pid" "$LLAMA_SWAP_PID_FILE"
