#!/usr/bin/env bash
# Chat UI layer (video chapter 2:55): AnythingLLM in Docker with host
# networking and a Docker-managed volume, mirroring the video. The script
# pulls the pinned image and starts the container; the LLM provider is then
# configured once in the web UI (checklist printed at the end).
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=_common.sh
source "$SCRIPT_DIR/_common.sh"
require_command docker
require_command curl
prepare_results

compose_dir="$STACK_DIR/anythingllm"
compose_file="$compose_dir/docker-compose.yml"
mkdir -p "$compose_dir"

cat >"$compose_file" <<EOF
# Generated by 04_setup_anythingllm.sh; edit config.env instead.
# network_mode host mirrors the video so the container reaches the engine at
# $ENGINE_BASE_URL directly. The UI is then reachable on port $ANYTHINGLLM_PORT
# of every host interface; see GUIDE.md section 4.3 for the safer variant.
services:
  anythingllm:
    image: $ANYTHINGLLM_IMAGE
    container_name: anythingllm
    network_mode: host
    cap_add:
      - SYS_ADMIN
    environment:
      - STORAGE_DIR=/app/server/storage
      - SERVER_PORT=$ANYTHINGLLM_PORT
    volumes:
      - anythingllm_storage:/app/server/storage
    restart: unless-stopped
volumes:
  anythingllm_storage:
EOF
printf 'Wrote compose file: %s\n' "$compose_file"

docker compose -f "$compose_file" pull
docker compose -f "$compose_file" up -d

if ! wait_http "http://127.0.0.1:$ANYTHINGLLM_PORT" 120; then
  printf 'AnythingLLM did not answer on port %s; inspect: docker logs anythingllm\n' \
    "$ANYTHINGLLM_PORT" >&2
  exit 1
fi

cat <<EOF

AnythingLLM is up: http://127.0.0.1:$ANYTHINGLLM_PORT (also on this host's LAN IP, as in the video).

One-time UI setup (video chapter 2:55), validation checkpoints in GUIDE.md:
  1. Open the URL, create the admin account, and skip onboarding offers.
  2. Settings -> AI Providers -> LLM -> Generic OpenAI.
  3. Base URL: $ENGINE_BASE_URL  (adapted: video used machine-IP:8080; this host's 8080 is taken and the engine binds loopback)
  4. API Key: any non-empty value (the engine does not require one unless LLAMA_API_KEY is set).
  5. Chat Model: select "$MODEL_ALIAS" (auto-listed from the engine).
  6. Token context window: $ENGINE_CTX. Max output tokens: 1024.
  7. Save, return to the workspace, and send "hi" - expect a reply from the local engine.
EOF
