#!/usr/bin/env bash
# Automation layer (video chapter 9:05): n8n in Docker with a Docker-managed
# volume, mirroring the video. The script pulls the pinned image and starts
# the container; credentials and the workflow are then built once in the web
# UI (checklist printed at the end).
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=_common.sh
source "$SCRIPT_DIR/_common.sh"
require_command docker
require_command curl
prepare_results

compose_dir="$STACK_DIR/n8n"
compose_file="$compose_dir/docker-compose.yml"
mkdir -p "$compose_dir"

cat >"$compose_file" <<EOF
# Generated by 07_setup_n8n.sh; edit config.env instead.
# network_mode host mirrors the video so workflow nodes reach the engine at
# $ENGINE_BASE_URL directly. The editor is then reachable on port $N8N_PORT of
# every host interface; see GUIDE.md section 4.6 for the safer variant.
services:
  n8n:
    image: $N8N_IMAGE
    container_name: n8n
    network_mode: host
    environment:
      - N8N_PORT=$N8N_PORT
      - GENERIC_TIMEZONE=$GENERIC_TIMEZONE
      - TZ=$GENERIC_TIMEZONE
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped
volumes:
  n8n_data:
EOF
printf 'Wrote compose file: %s\n' "$compose_file"

docker compose -f "$compose_file" pull
docker compose -f "$compose_file" up -d

if ! wait_http "http://127.0.0.1:$N8N_PORT/healthz" 180; then
  printf 'n8n did not answer on port %s; inspect: docker logs n8n\n' "$N8N_PORT" >&2
  exit 1
fi

cat <<EOF

n8n is up: http://127.0.0.1:$N8N_PORT (also on this host's LAN IP, as in the video).

One-time UI setup (video chapter 9:05), validation checkpoints in GUIDE.md:
  1. Open the URL and create the owner account (first run only).
  2. Credentials -> New -> OpenAI:
       Base URL: $ENGINE_BASE_URL/v1
       API Key:  any non-empty value (the video: "you can put any value in")
  3. New workflow:
       a. Trigger: Gmail Trigger (or Schedule Trigger) polling every hour.
       b. Add an AI Agent node; put the email subject + body into the user
          message and the triage instructions into the system message.
       c. Attach an OpenAI Chat Model subnode with the credential above;
          model "$MODEL_ALIAS"; disable "Use Responses API" if offered
          (this build also serves /v1/responses, but the video's standard
          chat-completions path is the verified one).
       d. Add the Gmail "add a label" tool pointing at the trigger's message
          ID, with a clear custom description for the agent.
  4. Success: executing the workflow labels a matching email; every model
     call stays on this machine (engine log shows the requests).
EOF
